ALTER TABLE Employees
    ADD COLUMN status VARCHAR(100) DEFAULT 'PENDING' NOT NULL CHECK (status IN (
        'ACCEPTED',
        'PENDING'
    ));

CREATE TABLE Invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL UNIQUE CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    token VARCHAR(300) NOT NULL,
    type VARCHAR(30) NOT NULL CHECK (type IN (
        'SALES_MANAGER', 'CLIENT_MANAGER', 'PURCHASING_MANAGER',
        'MUSICIAN', 'ACTOR', 'DRIVER', 'HOST', 'CHEF'
    )),
    salary NUMERIC(12, 2) NOT NULL CHECK (salary >= 0),
    role VARCHAR(100) NOT NULL CHECK (role IN (
        'ADMIN',
        'STAFF'
    ))
);