CREATE TABLE client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL
        CHECK (type IN ('PERSON', 'ORGANIZATION')),
    UNIQUE (id, type)
);

CREATE TABLE person (
    id BIGINT PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'PERSON'
        CHECK (type = 'PERSON'),
    personal_number VARCHAR(30) NOT NULL UNIQUE,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,

    FOREIGN KEY (id, type)
        REFERENCES client(id, type) ON DELETE CASCADE
);

CREATE TABLE organization (
    id BIGINT PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'ORGANIZATION'
        CHECK (type = 'ORGANIZATION'),
    organization_name VARCHAR(200) NOT NULL,
    organization_type VARCHAR(100) NOT NULL,
    manager VARCHAR(200) NOT NULL,
    contact_person VARCHAR(200) NOT NULL,

    FOREIGN KEY (id, type)
        REFERENCES client(id, type) ON DELETE CASCADE
);

CREATE TABLE supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_number VARCHAR(50) NOT NULL UNIQUE,
    product_type VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(200) NOT NULL,
    number VARCHAR(30) NOT NULL
);

-- Supplies: supplier 1:N product.
-- Quantity belongs to this relationship.
CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    supplier_id BIGINT NOT NULL REFERENCES supplier(id),
    quantity NUMERIC(12, 3) NOT NULL CHECK (quantity >= 0)
);

CREATE TABLE Vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(30) NOT NULL CHECK (type IN (
        'TRUCK',
        'PASSENGER_VEHICLE'
    )),
    passenger_capacity BIGINT NOT NULL
        CHECK (passenger_capacity >= 0),
    cargo_weight_limit NUMERIC(12, 2) NOT NULL
        CHECK (cargo_weight_limit >= 0)
);

-- Booked: client 1:N event.
-- Menu remains embedded in the event.
CREATE TABLE Event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client(id),
    client_name VARCHAR(100) NOT NULL,

    event_type VARCHAR(30) NOT NULL CHECK (event_type IN (
        'WEDDING',
        'CORPORATE EVENT',
        'CONFERENCE',
        'OFFICIAL RECEPTION',
        'ANNIVERSARY',
        'BIRTHDAY',
        'GALA DINNER',
        'PRODUCT LAUNCH',
        'PRIVATE PARTY',
        'OTHER'
    )),

    date DATE NOT NULL,
    total_cost NUMERIC(12, 2) NOT NULL CHECK (total_cost >= 0),
    guest_count INT NOT NULL CHECK (guest_count >= 0),

    location VARCHAR(100) NOT NULL CHECK (location IN (
        'AURUM BANQUET HALL',
        'AURUM CONFERENCE HALL',
        'PRIVATE RESIDENCE',
        'PARTNER VENUE',
        'HOTEL',
        'RESTAURANT',
        'OUTDOOR VENUE',
        'HISTORICAL VENUE',
        'CORPORATE OFFICE',
        'OTHER'
    )),

    cuisine_type VARCHAR(100) NOT NULL,
    appetizer VARCHAR(255) NOT NULL,
    main_course VARCHAR(255) NOT NULL,
    dessert VARCHAR(255) NOT NULL,
    drinks VARCHAR(255) NOT NULL
);

-- Weak entity: identified by its event and feedback id.
CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author VARCHAR(100) NOT NULL,
    event_id BIGINT NOT NULL
        REFERENCES Event(id) ON DELETE CASCADE,
    comment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    description TEXT NOT NULL,

    PRIMARY KEY (event_id, id)
);

-- Works: employee N:M event, with a role.
CREATE TABLE employee_event (
    employee_id BIGINT NOT NULL REFERENCES employees(id),
    event_id BIGINT NOT NULL
        REFERENCES Event(id) ON DELETE CASCADE,
    role VARCHAR(100) NOT NULL,

    PRIMARY KEY (employee_id, event_id)
);

-- Serves: vehicle N:M event.
CREATE TABLE vehicle_event (
    vehicle_id BIGINT NOT NULL REFERENCES Vehicle(id),
    event_id BIGINT NOT NULL
        REFERENCES Event(id) ON DELETE CASCADE,

    PRIMARY KEY (vehicle_id, event_id)
);

-- Used: product N:M event.
CREATE TABLE product_event (
    product_id BIGINT NOT NULL REFERENCES product(id),
    event_id BIGINT NOT NULL
        REFERENCES Event(id) ON DELETE CASCADE,

    PRIMARY KEY (product_id, event_id)
);

CREATE INDEX idx_product_supplier
    ON product(supplier_id);

CREATE INDEX idx_event_client
    ON Event(client_id);

CREATE INDEX idx_employee_event_event
    ON employee_event(event_id);

CREATE INDEX idx_vehicle_event_event
    ON vehicle_event(event_id);

CREATE INDEX idx_product_event_event
    ON product_event(event_id);