CREATE TABLE event_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    client_name VARCHAR(255) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(30) NOT NULL,

    event_type VARCHAR(30) NOT NULL CHECK (event_type IN (
        'WEDDING',
        'CORPORATE EVENT',
        'CONFERENCE',
        'OFFICIAL RECEPTION',
        'ANNIVERSARY',
        'BIRTHDAY',
        'GALA DINNER',
        'PRODUCT LAUNCH',
        'PRIVATE PARTY',
        'OTHER'
    )),

    preferred_date DATE NOT NULL,

    guest_count INT NOT NULL CHECK (guest_count > 0),

    location VARCHAR(100) NOT NULL CHECK (location IN (
        'AURUM BANQUET HALL',
        'AURUM CONFERENCE HALL',
        'PRIVATE RESIDENCE',
        'PARTNER VENUE',
        'HOTEL',
        'RESTAURANT',
        'OUTDOOR VENUE',
        'HISTORICAL VENUE',
        'CORPORATE OFFICE',
        'OTHER'
    )),

    approximate_budget NUMERIC(12, 2) NOT NULL
        CHECK (approximate_budget >= 0),

    notes VARCHAR(500),

    status VARCHAR(20) NOT NULL CHECK (status IN (
        'PENDING',
        'ACCEPTED',
        'REJECTED'
    ))
);