-- Remove the old plain-text menu fields from Event
ALTER TABLE event
    DROP COLUMN IF EXISTS appetizer,
    DROP COLUMN IF EXISTS main_course,
    DROP COLUMN IF EXISTS dessert,
    DROP COLUMN IF EXISTS drinks;


-- Create the menu item catalog
CREATE TABLE menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL,

    category VARCHAR(30) NOT NULL CHECK (category IN (
        'APPETIZER',
        'MAIN_COURSE',
        'DESSERT',
        'DRINK'
    )),

    price_per_person NUMERIC(10, 2) NOT NULL
        CHECK (price_per_person >= 0)
);


-- Connect Events and Menu Items (N:M)
CREATE TABLE event_menu_items (
    event_id BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,

    PRIMARY KEY (event_id, menu_item_id),

    CONSTRAINT fk_event_menu_items_event
        FOREIGN KEY (event_id)
        REFERENCES event(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_event_menu_items_menu_item
        FOREIGN KEY (menu_item_id)
        REFERENCES menu_items(id)
);


-- Useful when looking up all events containing a particular menu item
CREATE INDEX idx_event_menu_items_menu_item_id
    ON event_menu_items(menu_item_id);